--Creación de tablas
DROP TABLE CUOTAS_FINALES;
DROP TABLE CUOTAS_EXTRAORDINARIAS;
DROP TABLE CUOTAS_CONDOMINIALES;
DROP TABLE ACCESOS;
DROP TABLE FILIALES;
DROP TABLE PROPIETARIOS;
DROP TABLE PERSONAS;


SELECT * FROM CUOTAS_FINALES;
CREATE TABLE CONDOMINIO.PERSONAS (
    ID VARCHAR2(20) NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR2(50) ,
    APELLIDOS VARCHAR2(100),
    TELEFONO NUMBER(10),
    CORREO VARCHAR2(40));
COMMIT;

CREATE TABLE CONDOMINIO.PROPIETARIOS (
    COD_PROPIETARIO CHAR(5) NOT NULL PRIMARY KEY,
    ID_PERSONA VARCHAR2(20) NOT NULL,
    FECHA_ADQUISICION TIMESTAMP,
    CONSTRAINT PRO_PER_FK FOREIGN KEY (ID_PERSONA) REFERENCES 
    CONDOMINIO.PERSONAS (ID));
COMMIT;

CREATE TABLE CONDOMINIO.FILIALES (
    COD_FILIAL CHAR(5) NOT NULL PRIMARY KEY,
    COD_PROPIETARIO CHAR(5) NOT NULL,
    DESCRIPCION VARCHAR2(100),
    VALOR FLOAT,
    DIRECCION VARCHAR2(100),
    CONSTRAINT FIL_PRO_FK FOREIGN KEY (COD_PROPIETARIO) REFERENCES 
    CONDOMINIO.PROPIETARIOS (COD_PROPIETARIO));
COMMIT;

CREATE TABLE CONDOMINIO.ACCESOS (
    COD_ACCESO CHAR(5) NOT NULL PRIMARY KEY,
    COD_FILIAL CHAR(5) NOT NULL,
    ID_PERSONA VARCHAR2(20) NOT NULL, 
    TIPO_PERSONA VARCHAR2(15),
    FECHA_HORA TIMESTAMP,
    TIPO_ACCESO VARCHAR2(30),
    DETALLE VARCHAR2(100),
    CONSTRAINT ACC_PER_FK FOREIGN KEY (ID_PERSONA) REFERENCES 
    CONDOMINIO.PERSONAS (ID),
    CONSTRAINT ACC_FIL_FK FOREIGN KEY (COD_FILIAL) REFERENCES 
    CONDOMINIO.FILIALES (COD_FILIAL));
COMMIT;

CREATE TABLE CONDOMINIO.CUOTAS_CONDOMINIALES (
    COD_CUOTA_C CHAR(5) NOT NULL PRIMARY KEY,
    MONTO FLOAT,
    FECHA_VENCIMIENTO TIMESTAMP,
    DETALLE VARCHAR2(100));
COMMIT;

CREATE TABLE CONDOMINIO.CUOTAS_EXTRAORDINARIAS (
    COD_CUOTA_E CHAR(5) NOT NULL PRIMARY KEY,
    MONTO FLOAT,
    FECHA_EMISION TIMESTAMP,
    FECHA_VENCIMIENTO TIMESTAMP,
    DETALLE VARCHAR2(100));
COMMIT;

CREATE TABLE CONDOMINIO.CUOTAS_FINALES (
    COD_CUOTA CHAR(5) NOT NULL PRIMARY KEY,
    COD_FILIAL CHAR(5),
    COD_CUOTA_C CHAR(5) NOT NULL,
    COD_CUOTA_E CHAR(5),
    ESTADO VARCHAR2 (15),
    TOTAL FLOAT,
    IVA FLOAT,
    TOTAL_IVA FLOAT,
    CONSTRAINT FIN_FIL_FK FOREIGN KEY (COD_FILIAL) REFERENCES 
    CONDOMINIO.FILIALES (COD_FILIAL),
    CONSTRAINT FIN_CON_FK FOREIGN KEY (COD_CUOTA_C) REFERENCES 
    CONDOMINIO.CUOTAS_CONDOMINIALES (COD_CUOTA_C),
    CONSTRAINT FIN_EXT_FK FOREIGN KEY (COD_CUOTA_E) REFERENCES 
    CONDOMINIO.CUOTAS_EXTRAORDINARIAS (COD_CUOTA_E));
COMMIT;
