CREATE TABLESPACE CONDOMINIO_DATA
DATAFILE 'F:\DataFiles\CONDOMINIO_DATA.DBF' SIZE 100M
ONLINE;
CREATE TEMPORARY TABLESPACE CONDOMINIO_TEMP 
TEMPFILE 'F:\DataFiles\CONDOMINIO_TEMP.DBF' 
SIZE 25M
AUTOEXTEND ON ;
alter session set "_oracle_script" = true;
CREATE USER CONDOMINIO IDENTIFIED BY root284
       DEFAULT TABLESPACE CONDOMINIO_DATA
       TEMPORARY TABLESPACE CONDOMINIO_TEMP;
GRANT RESOURCE TO CONDOMINIO;
GRANT CONNECT TO CONDOMINIO;
GRANT CREATE SESSION TO CONDOMINIO;
GRANT ALL PRIVILEGES TO CONDOMINIO;